### PR TITLE
FAST Farm infrastructure improvements

### PR DESCRIPTION
**Pull request by rafmudaf**
**Feature or improvement description**
This pull request adds the regression test infrastructure as well as enables a single regression test (TSinflow) to run within GitHub Actions. It also updates the CMake configuration to search for the Fortran libraries of OpenMP rather than require the C and C++ libraries., as well.

I've also changed the name of the executable from `openfast-farm` to `fast-farm` for consistency with other references to this software.

**Impacted areas of the software**
FAST Farm CMake configuration and regression test infrastructure

**Additional information**
Its not ideal to have multiple copies of the 5MW turbine directory in r-test and multiple copies of the controllers. I'm looking at ways to simplify this, but in the meantime we can continue with the setup here.

Also, the test cases were initially created by @kshaler and updated by me in the `fastfarm` [branch of the r-test](https://github.com/OpenFAST/r-test/tree/fastfarm/glue-codes/fast-farm) repository.
the `LESinflow` test case is not yet enabled due to out of date input files.

For review: @jjonkman @kshaler

### CODE REVIEW

**Comment by rafmudaf** [comment]
The TSinflow regression test case generates many VTK files even though the WrVTK setting is 0 in all .fst files. Is there another flag to disable outputting these files?

**Comment by jjonkman** [comment]
@rafmudaf -- When running FAST.Farm, both FAST.Farm itself and the OpenFAST models it contains can generate VTK files.  It sounds like you've verified that the OpenFAST models are not generating VTK files, so, my guess is FAST.Farm itself is generating the disturbed wind data.  I would disable these for the purposes of the FAST.Farm r-test. You can stop generating these by setting WrDisWind = False and NOutDisWindXY, NOutDisWindYZ, and NOutDisWindXZ to 0 in the FAST.Farm input file.

**Comment by rafmudaf** [comment]
Ok I've made that change, thanks @jjonkman

**Comment by rafmudaf** [comment]
As for the LESinflow test case, the input files need to be updated to the latest version of OpenFAST but there's another issue:
```
 Farm_Initialize:AWAE_Init:ReadVTK_SP_info:Invalid vtk structured_points file: did not find
 VECTORS or FIELD label



  Aborting FAST.Farm.
```
The input files are in the r-test repository on the "fastfarm" branch ([here](https://github.com/OpenFAST/r-test/tree/fastfarm)).

**Comment by jjonkman** [comment]
@rafmudaf -- Looking at a couple of these VTK wind data files, it looks like 9th line is not formatted correctly.  There should not be a space before the "field" keyword.

**Comment by rafmudaf** [comment]
Removing that space in all of the VTK files leads to this error:
```
At line 8604 of file /Users/rmudafor/Development/fastfarm/modules/nwtc-library/src/NWTC_IO.f90
Fortran runtime error: Bad integer for item 1 in list input

Error termination. Backtrace:
#0  0x111a6bebd
#1  0x111a6cb75
#2  0x111a6d76b
#3  0x111c91008
#4  0x111c95019
#5  0x111c95bd2
#6  0x110781d55
#7  0x1107f2bbc
#8  0x1107e51d9
#9  0x10fc5c205
#10  0x10fcb10f3
#11  0x1112e85ce
```

**Comment by kshaler** [comment]
The space in the vtk files is standard. Can we change the source code to include the space?

**Comment by jjonkman** [comment]
@kshaler -- Where are you getting that a space before field is standard?  I don't see that in the VTK documentation, and all examples show FIELD showing up in the first column: https://vtk.org/wp-content/uploads/2015/04/file-formats.pdf.  Did you change this in your branch of FAST.Farm?

@rafmudaf -- I've not seen this error before.  Probably need to run this one through the debugger to understand what is going on.

**Comment by kshaler** [comment]
All the vtk files I have have that space in front of FIELD. So maybe it's changed somewhere in SOWFA?

**Comment by jjonkman** [comment]
@kshaler -- Yes, sounds like the problem is in SOWFA.  But I'm also not sure you've been running FAST.Farm with these files, unless you've changed the FAST.Farm source code on your branch accordingly; did you do that?

**Comment by jjonkman** [comment]
Hi @rafmudaf and @kshaler,

Thanks for developing these FAST.Farm r-tests!  I reviewed these a bit; here are some small changes I propose:

- It looks like the executable compiled with CMake is named `fast-farm` instead of `FAST.Farm`, which is compiled with Visual Studio.  Is there a reason for this difference? The FAST.Farm documentation uses the dot.  Can CMake be changed accordingly?
- It would be great if the duplicated files from the OpenFAST r-tests could be eliminated (the duplicated InflowWind, AeroDyn, and ElastoDyn input files for the NREL 5-MW baseline turbine; the duplicated _*.fst_ and ServoDyn files _are_ needed).
- The _LESinflow_ and _TSinflow_ directory structures are set up differently, with one having the OpenFAST model in a subdirectory and the other without.  I don't see any reason for this difference, so, I suggest organizing the file structure to be the same for both tests.
- The FAST.Farm input files (*.fstf) do not have the most up-to-date formatting regarding variable names and comments.  Can these be updated based on the attached template? [FAST.FarmInputFile.fstf.txt](https://github.com/jjonkman/OpenFAST/files/6093357/FAST.FarmInputFile.fstf.txt)
- For the _LESinflow_ case, I don't think high-resolution files beyond _Amb.t900.vtk_ are used because the simulation is only 90 s.  I suggest deleting the extra files (_Amb.t901.vtk_ through _Amb.t996.vtk_).
- For the _TSinflow_ case, I'm a bit confused where the dX_Low = 9.71 m comes from.  I calculate a mean wind speed of the TS wind field of 8*(175/85)^0.2 = 9.24 m/s, based on TS inputs in _90m_08mps.inp_.  With a time step of 0.1 s, this equates to a dX_Inflow of 0.924 m and 9.71/0.924 = 10.5, which is not an integer.  Also, I would expect dX_High = dX_Low in this case.
- The file _NRELOffshrBsline5MW_Onshore_ElastoDyn.dat_ does not appear to be used; suggest deleting.

What is left to push this?

**Comment by rafmudaf** [comment]
Thanks for the comments. My response to the points that relate to me are below.

- It looks like the executable compiled with CMake is named fast-farm instead of FAST.Farm, which is compiled with Visual Studio. Is there a reason for this difference? The FAST.Farm documentation uses the dot. Can CMake be changed accordingly?
  - I agree that the name of the executable should match what your team has in the documentation or have been previously using. I changed it from `openfast-farm` to `fast-farm` in https://github.com/jjonkman/OpenFAST/pull/15/commits/2776fdc6d038ec476663d803b2666d16ade3524a and again to `FAST.Farm` in https://github.com/jjonkman/OpenFAST/pull/15/commits/eb578ba574866772ef1689829f6bcfcec94da96c. This last commit can be referenced if the binary name needs adjusting in CMake in the future.
- It would be great if the duplicated files from the OpenFAST r-tests could be eliminated (the duplicated InflowWind, AeroDyn, and ElastoDyn input files for the NREL 5-MW baseline turbine; the duplicated *.fst and ServoDyn files are needed)
  - The automated test system requires this so that the FAST.Farm tests do not depend on the OpenFAST tests. This is a limitation of the regression test system, but I'm working on solving that problem in the larger context. Let's keep it as is for now, but it will be resolved in the near future.
- The file NRELOffshrBsline5MW_Onshore_ElastoDyn.dat does not appear to be used; suggest deleting.
  - Good catch, its been removed

**Comment by rafmudaf** [comment]
From an infrastructure perspective, I think the only thing remaining is updating the LESinflow test so that it can run with this version of FAST Farm and also addressing @jjonkman's comments.

**Comment by jjonkman** [comment]
Thanks, @rafmudaf.  Can you also help with bullets 3-5?  This requires moving files around and ensuring the paths and formatting are set up correctly in the input files.

I've now fixed the error that was causing FAST.Farm to fail when the FIELD keyword was used on line 9 of the VTK files--see: https://github.com/jjonkman/OpenFAST/commit/25f89af8a3b4749be67a542633b2cb9c938f1408.  This should now enable the _LESinflow_ case to run. (However, there still cannot be a space before FIELD keyword.)  FAST.Farm now reads the VTK files OK, but I noticed the OpenFAST input files for this test are old, not having yet been upgraded to a format compatible with the dev branch.  @rafmudaf -- Can you update the files for this case and ensure it runs to completion?

@kshaler -- Please respond regarding dX_Low and dX_High from bullet 6.

**Comment by kshaler** [comment]
I've updated the FAST.Farm input file to have the correct discretization values.

**Comment by jjonkman** [comment]
Thanks @kshaler.

@rafmudaf -- Can you merge Kelsey's change for the TSinflow case and address bullets 3-5 in the r-test?  Hopefully FAST.Farm will then execute these cases as expected.

**Comment by rafmudaf** [comment]
@jjonkman I've addressed those three items in your list in https://github.com/jjonkman/OpenFAST/pull/15/commits/631602fff0bdd6ed3556b0f7488a6e402b78f176.

**Comment by rafmudaf** [comment]
~Anyone know why GitHub Actions isn't running?~

Actions is unavailable: https://www.githubstatus.com

Update 3/16/21: I made a small change to the GH Actions workflow to trigger the tests to run.

**Comment by rafmudaf** [comment]
@jjonkman the automated tests have passed, so this is ready for review.

**Pull request merged**
