### PR TITLE
F/ff openmp vtk

### PR DESCRIPTION
**Pull request by ebranlard**
Ready to merge. 

- vtk are written in folder vtk_ff
- timestamp of vtk with 0-padding
- OpenMP is shown during NWTC_Init
- Comment line argument fixed (again),  the program aborts if not arguments provided, the program stop normally if flags are present.  (otherwise there were still duplicate of banners).

### CODE REVIEW

**Comment by jjonkman** [comment]
Thanks, @ebranlard.  I just reviewed this.  Can I suggest three minor improvements?:

1.  In the calculation of VTK_tWidth, NumDT needs to be divided by WrDisSkp1
2. Can the format string used to write Tstr be made a parameter?  The call to Num2LStr() can take a long time.
3. Now the VTK files written by FAST.Farm are named with leading zeros and no t, but the VTK inputs to FAST.Farm are unchanged from before.  Shouldn't these be consistent?

Thanks,

**Comment by ebranlard** [comment]
Thanks for the comments:
1. I've fixed that
2. This is the way it's done in OpenFAST ( `FAST_Subs.f90`), I think it's fair
3. It's true, but I'd skip this for now. I've changed the extension to be consistent with how FAST outputs VTKs. Now it's a bit unfortunate that the inputs to fast farm are not like this. It would make sense to change them, we would need to infer the number of padding zeros from the user inputs. No matter what, I think it's important to have the outputs with 0-padding and same field name so that they can more readily be imported in Paraview.

**Comment by jjonkman** [comment]
OK, thank you.  I think you need to change the calculation of VTK_tWidth to be REAL(p%NumDT,ReKi)/REAL(p%WrDisSkp1,ReKi) because the integer division will be performed first (and NumDT may not be an integer multiple of WrDisSkp1).

I'll update the FF documentation and make a note of the issue to change the input ambient VTK naming to match the output disturbed VTK naming.

**Comment by ebranlard** [comment]
I've updated the division in my new commit. I actually remember having a flinch when writing it, but settled thinking that the log10, the ceiling and the +1 would most likely take care of round off errors from the integer division. 

Sounds good, if we change the inputs, we can try to provide a renaming script for the users.

**Comment by jjonkman** [comment]
Thanks; merged!

**Pull request merged**
